#!/usr/bin/env python3
"""Writes app/strings.js: the board's texts (the «app_» strings of a language pack, with English for anything
missing), for the screen outside Moodle (the SCORM package and local tests). Inside Moodle the page gets them from
the language packs directly, in each user's language.

Usage: tools/strings.py [lang] [output]    (defaults: en, app/strings.js)
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(lang):
    path = os.path.join(HERE, 'lang', lang, 'local_oksigeniaclasstools.php')
    if not os.path.exists(path):
        return {}
    text = open(path, encoding='utf-8').read()
    strings = {}
    for key, value in re.findall(r"\$string\['([^']+)'\]\s*=\s*'((?:[^'\\]|\\.)*)';", text, re.S):
        if key.startswith('app_'):
            strings[key[4:]] = re.sub(r"\\([\\'])", r'\1', value)
    return strings


def main():
    lang = sys.argv[1] if len(sys.argv) > 1 else 'en'
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, 'app', 'strings.js')
    strings = load('en')
    strings.update(load(lang))
    body = json.dumps(dict(sorted(strings.items())), ensure_ascii=False, indent=0)
    with open(out, 'w', encoding='utf-8') as f:
        f.write(f"// The board's texts ({lang}), generated by tools/strings.py from the language packs: do not edit.\n"
                "// Inside Moodle each user gets them in their own language instead.\n'use strict';\n"
                f"window.CLASSTOOLS_LANG = '{lang}';\n"
                f"window.CLASSTOOLS_STR = {body};\n")
    print(f'{out}: {len(strings)} strings ({lang})')


main()
